[project]
name = "llm-from-scratch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "tiktoken>=0.9.0",
]

[dependency-groups]
dev = [
    "ipykernel>=6.30.0",
]
